# Generated by Django 2.1.2 on 2018-10-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20181015_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Post categories')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('add3', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=False)),
                ('payment_type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date order')),
                ('status', models.BooleanField(default=False)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.categories')),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='add3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logins',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.delivery_addresses'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.orders'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.products'),
        ),
    ]
