# Generated by Django 2.1.2 on 2018-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20181017_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Post products'),
            preserve_default=False,
        ),
    ]
