# Generated by Django 2.1.2 on 2018-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20181018_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
